#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('PHP Snowflake', '0.1.0');

$app->add(new LucasVscn\Snowflake\Console\ServerCommand);
$app->add(new LucasVscn\Snowflake\Console\NextIdCommand);

$app->run();